### PR TITLE
just repair work following UniMath PR #1507

### PR DESCRIPTION
**Pull request by rmatthes**
On my system, this is enough to make this satellite compile again.

### CODE REVIEW

**Comment by rmatthes** [comment]
`coq_makefile: command not found` in the output of CI suggests that there is a configuration problem

**Comment by benediktahrens** [comment]
Thanks a lot for this PR. Could you rebase on top of current master, so that the CI fix #5 is included?

**Comment by rmatthes** [comment]
This was a micro-PR relative to the amount of repair work for the other parts of the system. I truly wanted to see successful CI for UniMath master again.

**Comment by rmatthes** [comment]
There appears to be another problem with the CI configuration.

**Comment by benediktahrens** [comment]
Sorry for that, see https://github.com/UniMath/SetHITs/pull/6 (merged already).

**Comment by benediktahrens** [comment]
@rmatthes : thanks for the reminder!

**Pull request merged**
